### ISSUE TITLE
выравнивание

### ISSUE THREAD

**Issue by Vombatt** [Lusyena/Avenue_Fashion#23]
![image](https://user-images.githubusercontent.com/30000201/62818741-09593900-bb54-11e9-9bb8-bac4fc938453.png)
сейчас ты задаешь положение для сепаратора, меню и блока с фотографиями в каждом случае отдельно, это не очень хорошо. Объедини все это в один контейнер и задай положение для него один раз. Также обрати внимание на то, что ширина этого контейнера должна совпадать, с шириной main-menu

**Comment by Lusyena** [comment]
+
